Metadata: sample.csv

raw_data:
  fastq: data/fastq

fastqc:
  run: True
  output: data/fastqc

trimming:   # Experimental feature
  run: True
  output: data/fastq_trimmed

kraken2:
  run: True
  db_parent_dir: /bigdata/stajichlab/shared/db/kraken2
  db: RefSeq_fungi_bac
  output: data/kraken2

assembly:
  run: True
  assembler: spades    # Available choices ['spades', 'megahit']
  output: data/spades
  # output: data/megahit
  min_contig_length: 3000
  filtered_contigs: data/filtered_contigs

autometa:
  run: True
  databases: /rhome/ctsai085/bigdata/databases/autometa/databases
  output: data/autometa
  binning_target: ['bacteria']    # Available options ['bacteria', 'archaea']
  unclustered_recruitment: False   # Experimental features

align_MAGs:
  run: True
  tools: 'bowtie2'       # Available choices ['bbmap', 'bowtie2']
  output: data/bowtie2
  # output: data/bbmap

