Metadata: config/sample.csv

# Use the highmem partion when slurm profile is specified
partition:
  highmem: highmem

raw_data:
  fastq: data/fastq

fastqc:
  run: True
  output: data/fastqc

trimming:
  run: True

kraken2:
  run: True
  db_parent_dir: /bigdata/stajichlab/shared/db/kraken2
  db: RefSeq_fungi_bac
  output: data/kraken2

mmseqs2:
  run: True
  db: /srv/projects/db/ncbi/mmseqs/uniref90
  output: data/mmseqs2

assembly:
  run: True
  assembler: spades    # Available choices ['spades', 'megahit']
  output: data/spades
  # output: data/megahit
  min_contig_length: 3000
  filtered_contigs: data/filtered_contigs

align_to_assembly:
  run: True
  tools: 'bowtie2'       # Available choices ['bbmap', 'bowtie2']
  output: data/bowtie2
  # output: data/bbmap

autometa:
  run: True
  databases: /rhome/ctsai085/bigdata/databases/autometa/databases
  output: data/autometa
  binning_target: ['bacteria']    # Available options ['bacteria', 'archaea']
  unclustered_recruitment: False   # Experimental features

metabat:
  run: True
  output: data/metabat

gtdbtk:
  run: True
  output: data/gtdbtk
  db: /srv/projects/db/gtdbtk/207_v2
  mash_db: /rhome/ctsai085/bigdata/databases/gtdbtk

functional_annotation:
  run: True
  clustering: False
  tools: ['dbcan', 'kofamscan']  # Available options ['dbcan', kofamscan']
  output: data/functional_annotation
  dbcan:
    db: /srv/projects/db/CAZY/CAZyDB/v11.0
  kofamscan:
    profile: ~/bigdata/databases/kofam/profiles/prokaryote.hal
    ko_list: ~/bigdata/databases/kofam/ko_list
